### PR TITLE
operator can set min delta to cut-off low delta option trading

### PR DESCRIPTION
**Pull request by predy-dev**
What
 * trader can not trade options whose delta is lower than min delta
 * operator can set min delta

### CODE REVIEW

**Comment by qxet** [comment]
where can operator set minDelta?

**Comment by predy-dev** [comment]
> where can operator set minDelta?

@qxet operator can set MinDelta config by calling setConfig function with key=MIN_DELTA.

**Comment by qxet** [comment]
I see, I thought some change has been made to enable that. But field is just added.

**Comment by qxet** [comment]
LGTM

**Pull request merged**
